name:                env-builder 
version:             0.1.0.0

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- mtl 
- postgresql-simple
- resource-pool
- bytestring 

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
